# Generated by Django 4.1.5 on 2023-02-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_my_profile_age_alter_my_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
