# Generated by Django 4.1.5 on 2023-02-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_my_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
