# Generated by Django 4.1.5 on 2023-02-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='property_image',
            field=models.ImageField(blank=True, default='defaultproperty.jpg', null=True, upload_to=''),
        ),
    ]
