# Generated by Django 4.1.5 on 2023-03-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_listing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
